import TypePM.Names
import TypePM.Primitive
import TypePM.Types
import TypePM.Syntax
import TypePM.Substitution
import TypePM.Checking
import TypePM.Typing
import TypePM.Fresh
import TypePM.Constraints
import TypePM.Generation
import TypePM.GenerationRelation
import TypePM.GenerationFreshness
import TypePM.FreeVars
import TypePM.Unification
import TypePM.UnificationCorrectness
import TypePM.UnificationTermination
import TypePM.UnificationSupport
import TypePM.Solver
import TypePM.SolverCertified
import TypePM.UnificationRegression
import TypePM.Resolution
import TypePM.ConversionPotential
import TypePM.Saturation
import TypePM.NoGuess
import TypePM.MGUEquivalence
import TypePM.SaturationUniqueness
import TypePM.Permutation
import TypePM.SourcePermutation
import TypePM.GenerationRenaming
import TypePM.ResolutionTransport
import TypePM.SaturationRenaming
import TypePM.BlockOrderInvariance
import TypePM.SaturationProcedure
import TypePM.SaturationProcedureCompleteness
import TypePM.Declarative
import TypePM.DeclarativeCoverage
import TypePM.InferenceProcedure
import TypePM.Inference
import TypePM.InferenceCompleteness
import TypePM.InferenceExactness
import TypePM.Principality
import TypePM.RenamingUniqueness
import TypePM.Regression
import TypePM.M1Examples
import TypePM.M1BoundaryRegression
import TypePM.BlockClosure
import TypePM.AbsorbingUnification
import TypePM.AbsorbingBlockClosure
import TypePM.AbsorbingSupportRange
import TypePM.GeneratedSupport
import TypePM.ResolutionSupport
import TypePM.BlockClosureSupport
import TypePM.Scheme
import TypePM.ContextInterface
import TypePM.ContextInterfaceRegression
import TypePM.SchemeTransport
import TypePM.GeneralizationTransport
import TypePM.BlockClosureTransport
import TypePM.HardWorklistEquivalence
import TypePM.FreshAliasElimination
import TypePM.FreshAliasSaturation
import TypePM.FreshAliasSequence
import TypePM.Source.Syntax
import TypePM.Source.Elaboration
import TypePM.Source.LocalizedClosure
import TypePM.Source.SupplyWellFormed
import TypePM.Source.SchemeSupportBounds
import TypePM.Source.GeneratedSupportBounds
import TypePM.Source.ContextInterfaceSupport
import TypePM.Source.LetSupplyStability
import TypePM.Source.ElaborationTransport
import TypePM.Source.ElaborationRenaming
import TypePM.Source.InterfaceClosureTransport
import TypePM.Source.FreshIntervalRenaming
import TypePM.Source.FinitePartialRenaming
import TypePM.Source.AlignmentComposition
import TypePM.Source.GeneratedAcceptanceTransport
import TypePM.Source.ClosureSupportRenaming
import TypePM.Source.InterfaceAliasCounterexample
import TypePM.Source.InterfaceAliasDecomposition
import TypePM.Source.InterfaceAliasFreshness
import TypePM.Source.GlobalRenamingCounterexample
import TypePM.Source.UnwellFormedSupplyPrincipalityCounterexample
import TypePM.Source.ScopedGeneratedEquivalence
import TypePM.Source.ScopedElaborationComposition
import TypePM.Source.RecursiveLetInvariant
import TypePM.Source.CrossGeneratedLetNormalization
import TypePM.Source.RecursiveLetSupportSafety
import TypePM.Source.DirectLetComparison
import TypePM.Source.SourceSafeAlignmentCounterexample
import TypePM.Source.ElaborationCompleteness
import TypePM.Source.Principality
import TypePM.Source.ConditionalPrincipality
import TypePM.Source.M2Regression
import TypePM.Source.M3Regression
import TypePM.DataTypes
import TypePM.Constructors
import TypePM.Primitives
import TypePM.PatternDeclarations
import TypePM.Signature
import TypePM.M3DeclarationsRegression
import TypePM.Source.FrozenSignature
import TypePM.Source.M4FrozenSignatureRegression
import TypePM.Source.MatcherPattern
import TypePM.Source.M4MatcherPatternRegression
import TypePM.Runtime.OrderedChoice
import TypePM.Runtime.OrderedChoiceRegression
import TypePM.Runtime.OrderedChoiceAdequacy
import TypePM.Runtime.FuelResult
import TypePM.Runtime.FuelResultRegression
import TypePM.Runtime.OrderedDispatch
import TypePM.Runtime.OrderedDispatchRegression
import TypePM.Runtime.Environment
import TypePM.Runtime.EnvironmentRegression
import TypePM.Runtime.DepthFirstSearch
import TypePM.Runtime.DepthFirstSearchRegression
import TypePM.Runtime.GroundValue
import TypePM.Runtime.DataPattern
import TypePM.Runtime.DataPatternRegression
import TypePM.Runtime.PatternPattern
import TypePM.Runtime.PatternPatternRegression
import TypePM.Runtime.GroundPrimitive
import TypePM.Runtime.GroundPrimitiveAdequacy
import TypePM.Runtime.GroundPrimitiveRegression
import TypePM.Runtime.Values
import TypePM.Runtime.ValuesRegression
import TypePM.Runtime.ValueShape
import TypePM.Runtime.ValueShapeRegression
import TypePM.Runtime.MatchingState
import TypePM.Runtime.MatchingStateRegression
import TypePM.Runtime.MatchingSearch
import TypePM.Runtime.MatchingSearchRegression
import TypePM.Runtime.CombinedAtomReducer
import TypePM.Runtime.CombinedAtomReducerRegression
import TypePM.Runtime.ValueDataPattern
import TypePM.Runtime.ValueDataPatternRegression
import TypePM.Source.MatcherClauseShape
import TypePM.Source.M4MatcherClauseShapeRegression
import TypePM.Source.M4SyntaxRegression
import TypePM.Source.M4Elaboration
import TypePM.Source.M4PatternTypingRegression
import TypePM.AxiomAudit

/-!
# Type-PM

Independent mechanization of the new Type-PM design.  This root imports only
modules belonging to the new development.
-/
