import TypePM.Names
import TypePM.Primitive
import TypePM.InferenceExactness
import TypePM.Principality
import TypePM.RenamingUniqueness
import TypePM.NoGuess
import TypePM.SourcePermutation
import TypePM.GenerationRenaming
import TypePM.SaturationRenaming
import TypePM.BlockOrderInvariance
import TypePM.UnificationRegression
import TypePM.UnificationSupport
import TypePM.Regression
import TypePM.M1BoundaryRegression
import TypePM.BlockClosureTransport
import TypePM.AbsorbingSupportRange
import TypePM.GeneratedSupport
import TypePM.ResolutionSupport
import TypePM.BlockClosureSupport
import TypePM.ContextInterfaceRegression
import TypePM.M3DeclarationsRegression
import TypePM.Source.M4FrozenSignatureRegression
import TypePM.Source.M4MatcherPatternRegression
import TypePM.GeneralizationTransport
import TypePM.HardWorklistEquivalence
import TypePM.FreshAliasElimination
import TypePM.FreshAliasSaturation
import TypePM.FreshAliasSequence
import TypePM.Source.ElaborationTransport
import TypePM.Source.LocalizedClosure
import TypePM.Source.SupplyWellFormed
import TypePM.Source.SchemeSupportBounds
import TypePM.Source.GeneratedSupportBounds
import TypePM.Source.ContextInterfaceSupport
import TypePM.Source.LetSupplyStability
import TypePM.Source.ElaborationRenaming
import TypePM.Source.InterfaceClosureTransport
import TypePM.Source.FreshIntervalRenaming
import TypePM.Source.FinitePartialRenaming
import TypePM.Source.AlignmentComposition
import TypePM.Source.GeneratedAcceptanceTransport
import TypePM.Source.ClosureSupportRenaming
import TypePM.Source.InterfaceAliasCounterexample
import TypePM.Source.InterfaceAliasDecomposition
import TypePM.Source.InterfaceAliasFreshness
import TypePM.Source.GlobalRenamingCounterexample
import TypePM.Source.UnwellFormedSupplyPrincipalityCounterexample
import TypePM.Source.ScopedGeneratedEquivalence
import TypePM.Source.ScopedElaborationComposition
import TypePM.Source.RecursiveLetInvariant
import TypePM.Source.CrossGeneratedLetNormalization
import TypePM.Source.RecursiveLetSupportSafety
import TypePM.Source.SourceSafeAlignmentCounterexample
import TypePM.Source.ElaborationCompleteness
import TypePM.Source.Principality
import TypePM.Source.ConditionalPrincipality
import TypePM.Source.M2Regression

/-!
# Axiom audit for public milestones

These commands make the trusted assumptions of selected public results visible in
every full build.
-/

#print axioms TypePM.DataCtor.canonical_pairwise_distinct
#print axioms TypePM.PatternCtor.canonical_pairwise_distinct
#print axioms TypePM.NamesRegression.nil_spellings_agree
#print axioms TypePM.PrimOp.all_pairwise_distinct
#print axioms TypePM.Cap.apply_compose
#print axioms TypePM.Ty.apply_compose
#print axioms TypePM.Regression.pair_principal
#print axioms TypePM.Regression.pair_checks_as_slot
#print axioms TypePM.Regression.structured_matcher_checks_at_any_slot
#print axioms TypePM.unify_none_iff_unsatisfiable
#print axioms TypePM.unify_completeMGUSolver
#print axioms TypePM.UnificationRegression.con_same_former_and_arity_succeeds
#print axioms TypePM.UnificationRegression.data_same_former_and_arity_succeeds
#print axioms TypePM.UnificationRegression.con_name_mismatch_rejected
#print axioms TypePM.UnificationRegression.data_name_mismatch_rejected
#print axioms TypePM.UnificationRegression.con_arity_mismatch_rejected
#print axioms TypePM.UnificationRegression.data_arity_mismatch_rejected
#print axioms TypePM.unify_localized
#print axioms TypePM.Subst.Localized.compose
#print axioms TypePM.AbsorbingPrincipal.localized
#print axioms TypePM.promoteUnder_equation_no_special_after
#print axioms TypePM.Resolution.special_expected_head
#print axioms TypePM.Resolution.resolve_apply_canonical_of_retract
#print axioms TypePM.ResolutionTransport.residualEquations_transport_of_mutualFactors
#print axioms TypePM.Inference.infer_success_typing
#print axioms TypePM.Typing.infer_isSome
#print axioms TypePM.Inference.typable_iff_infer_isSome
#print axioms TypePM.Inference.typableDecidable
#print axioms TypePM.Inference.infer_principal
#print axioms TypePM.Inference.infer_success_principalTyping
#print axioms TypePM.PrincipalTyping.finiteRenaming_unique
#print axioms TypePM.GeneratedItems.siblingAlphaEq_collect_of_perm
#print axioms TypePM.solves_rename_perm
#print axioms TypePM.GeneratesItems.swapAdjacentPair
#print axioms TypePM.Saturated.permuteInitial
#print axioms TypePM.TypingDerivation.transportAlphaEq
#print axioms TypePM.Generated.AlphaEq.blockAccepts_iff
#print axioms TypePM.M1BoundaryRegression.infer_useFirst_exact
#print axioms TypePM.M1BoundaryRegression.infer_applicationFirst_exact
#print axioms TypePM.M1BoundaryRegression.infer_singletonFirst_none
#print axioms TypePM.M1BoundaryRegression.infer_pairFirst_none
#print axioms TypePM.M1BoundaryRegression.infer_pair_exact_raw_product
#print axioms TypePM.M1BoundaryRegression.singletonFirst_not_typable
#print axioms TypePM.M1BoundaryRegression.pairFirst_not_typable
#print axioms TypePM.unify_absorbingPrincipal
#print axioms TypePM.PrincipalBlockClosure.substitution_absorbingPrincipal
#print axioms TypePM.Resolution.equations_support
#print axioms TypePM.CheckObligation.mem_unificationVars_expected
#print axioms TypePM.Generated.saturationSupport_subset
#print axioms TypePM.PrincipalBlockClosure.localized_of_absorbing
#print axioms TypePM.inferGeneratedUsing_unify_localizedPrincipalBlockClosure
#print axioms TypePM.Source.Scheme.wellFormed
#print axioms TypePM.Source.Scheme.applyFree_id
#print axioms TypePM.Source.Scheme.instantiate_sound
#print axioms TypePM.Source.Context.generalize_wellFormed
#print axioms TypePM.Source.Context.generalize_instantiates
#print axioms TypePM.Source.Context.solves_interfaceEquations_iff
#print axioms TypePM.Source.Context.applyFree_interface_transport
#print axioms TypePM.Source.Context.generalize_variableRenaming
#print axioms TypePM.Source.Context.generalize_variableRenaming_exact
#print axioms TypePM.Source.Scheme.instantiate_ty_origin
#print axioms TypePM.Source.Scheme.instantiate_cap_origin
#print axioms TypePM.Source.Context.applyFree_initialSupply_le_of_localized
#print axioms TypePM.Source.Elaborates.supply_le_next
#print axioms TypePM.Source.Elaborates.supportProvenance
#print axioms TypePM.Source.ElaboratesItems.supportProvenance
#print axioms TypePM.Source.Elaborates.support_below
#print axioms TypePM.Source.Context.interfaceEquations_supportProvenance
#print axioms TypePM.Source.GeneratedSupportProvenance.fromLet_interface
#print axioms TypePM.Source.PrincipalBlockClosure.letBodySupply_eq
#print axioms TypePM.Source.Elaborates.letBodySupply_eq
#print axioms TypePM.Source.PrincipalTyping.localizedClosure
#print axioms TypePM.Source.ContextInterfaceRegression.swapBoth_notAbsorbing
#print axioms TypePM.Source.ContextInterfaceRegression.plainMostGeneral_can_create_spurious_interface_failure
#print axioms TypePM.PrincipalBlockClosure.representativeTransport
#print axioms TypePM.PrincipalBlockClosure.RepresentativeTransportUsing.context_forward
#print axioms TypePM.Source.Inference.infer_success_principalTyping
#print axioms TypePM.Source.Inference.infer_success_typing
#print axioms TypePM.Source.M2Regression.infer_polymorphicIdentity_exact
#print axioms TypePM.Source.M2Regression.polymorphicIdentityTyping
#print axioms TypePM.Source.M2Regression.infer_explicitLet_exact
#print axioms TypePM.Source.M2Regression.explicitLetTyping
#print axioms TypePM.Source.M2Regression.infer_cutRejectsBackflow_none
#print axioms TypePM.BlockAccepts.iff_of_hardEquivalent
#print axioms TypePM.FreshAliasElimination.blockAccepts_addTyAlias_iff_of_noPending
#print axioms TypePM.FreshAliasElimination.blockAccepts_addCapAlias_iff_of_noPending
#print axioms TypePM.FreshAliasSaturation.blockAccepts_addTyAlias_iff
#print axioms TypePM.FreshAliasSaturation.blockAccepts_addCapAlias_iff
#print axioms TypePM.FreshAliasSequence.CommonCoreEquivalent.blockAccepts_iff
#print axioms TypePM.Source.ElaborationRenaming.fromLet_otherClosure_blockAccepts_iff_of_freshAliasSequence
#print axioms TypePM.Source.InterfaceAliasCounterexample.no_left_addition_decomposition
#print axioms TypePM.Source.InterfaceAliasCounterexample.commonCoreEquivalent_positive
#print axioms TypePM.Source.InterfaceAliasDecomposition.AliasFreshness.admissible_of_scopedBy
#print axioms TypePM.Source.InterfaceAliasDecomposition.ClosureInterfaceDecomposition.targets_mutualInstances
#print axioms TypePM.Source.InterfaceAliasDecomposition.ClosureInterfaceDecomposition.fromLet_blockAccepts_iff
#print axioms TypePM.Source.InterfaceAliasDecomposition.Automatic.interfaceEndpointScopedBy
#print axioms TypePM.Source.InterfaceAliasDecomposition.Automatic.FreshClosureInterfaceDecomposition.admissible_of_avoids
#print axioms TypePM.Source.GlobalRenamingCounterexample.executable_elaborates
#print axioms TypePM.Source.GlobalRenamingCounterexample.alternative_elaborates
#print axioms TypePM.Source.GlobalRenamingCounterexample.no_global_renaming
#print axioms TypePM.Source.UnwellFormedSupplyPrincipalityCounterexample.reverseUnify_absorbingMGUSolver
#print axioms TypePM.Source.UnwellFormedSupplyPrincipalityCounterexample.targets_not_mutualInstances
#print axioms TypePM.Source.UnwellFormedSupplyPrincipalityCounterexample.badSupply_not_wellFormed
#print axioms TypePM.Source.Generated.ScopedContextualEquivalent.blockAccepts_iff
#print axioms TypePM.Source.Elaborates.sequential_crossAvoidance
#print axioms TypePM.Source.Elaborates.scopedComparison
#print axioms TypePM.Source.ElaboratesItems.scopedComparison
#print axioms TypePM.Source.Elaborates.scopedComparison_of_letFree
#print axioms TypePM.Source.Elaborates.alignment_of_fixesAtOrAbove
#print axioms TypePM.Source.Elaborates.transport_of_fixesAtOrAbove
#print axioms TypePM.Source.GeneratedEquationCommonCore.scopedContextualEquivalent_of_frameAdmissible
#print axioms TypePM.Source.scopedLetStep
#print axioms TypePM.Source.CrossGeneratedClosureAlignment.fromLet_blockAccepts_iff
#print axioms TypePM.Source.CrossGeneratedClosureAlignment.fromLet_targets_mutualInstances
#print axioms TypePM.Source.CrossGeneratedClosureAlignment.renamedFromLet_pending_exact
#print axioms TypePM.Source.IsolatedRenamingCounterexample.not_scopedContextualEquivalent
#print axioms TypePM.Source.VariableRenaming.FixesOutside.renameGenerated_eq
#print axioms TypePM.Source.GeneratedFrame.renameGenerated_plug_of_fixesOutside
#print axioms TypePM.Source.Generated.scopedContextualEquivalent_rename_of_fixesOutside
#print axioms TypePM.Source.Elaborates.generatedAvoids_earlierHidden
#print axioms TypePM.Source.SourceSafeWholeLetAlignment.scopedContextualEquivalent
#print axioms TypePM.Source.SourceSafeWholeLetAlignment.interfaceComparison
#print axioms TypePM.Source.FrameAdmissibilityCounterexample.not_frameAdmissible
#print axioms TypePM.Source.FutureFixingCounterexample.no_fresh_fixesOutside
#print axioms TypePM.Source.SourceSafeAlignmentCounterexample.no_supported_target_alignment
#print axioms TypePM.Source.SourceSafeAlignmentCounterexample.value_elaborates
#print axioms TypePM.Source.SourceSafeAlignmentCounterexample.valueStart_wellFormed
#print axioms TypePM.Source.SourceSafeAlignmentCounterexample.inherited_let_elaborates
#print axioms TypePM.Source.SourceSafeAlignmentCounterexample.representative_let_elaborates
#print axioms TypePM.Source.SourceSafeAlignmentCounterexample.actual_no_sourceSafeWholeLetAlignment
#print axioms TypePM.Source.Scheme.instantiate_variableRenaming_prefix
#print axioms TypePM.Source.ElaborationRenaming.Alignment.transport
#print axioms TypePM.Source.ElaborationRenaming.Generated.RenamedBy.blockAccepts_iff
#print axioms TypePM.Source.PrincipalBlockClosure.postcompose_solves_other_fromLet_hard_iff
#print axioms TypePM.Source.PrincipalBlockClosure.RepresentativeTransportUsing.closedContext_globalRenaming
#print axioms TypePM.BlockAccepts.inferGeneratedUsing_isSome
#print axioms TypePM.Source.Typing.infer_isSome_of_letFree
#print axioms TypePM.Source.Inference.typable_iff_infer_isSome_of_letFree
#print axioms TypePM.Source.Inference.typableDecidable_of_letFree
#print axioms TypePM.Source.Inference.infer_success_principalResult_of_letFree
#print axioms TypePM.Source.PrincipalTyping.finiteRenamingEq_of_letFree
#print axioms TypePM.Source.WellFormedElaborationPrincipalityComplete.toAcceptance
#print axioms TypePM.Source.Typing.infer_isSome_of_wellFormedElaborationAcceptanceComplete
#print axioms TypePM.Source.Inference.typable_iff_infer_isSome_of_wellFormedElaborationAcceptanceComplete
#print axioms TypePM.Source.Inference.typableDecidable_of_wellFormedElaborationAcceptanceComplete
#print axioms TypePM.Source.Typing.infer_isSome_of_wellFormedElaborationPrincipalityComplete
#print axioms TypePM.Source.Inference.typable_iff_infer_isSome_of_wellFormedElaborationPrincipalityComplete
#print axioms TypePM.Source.Inference.typableDecidable_of_wellFormedElaborationPrincipalityComplete
#print axioms TypePM.Source.Inference.infer_success_principalResult_of_wellFormedElaborationPrincipalityComplete
#print axioms TypePM.Source.PrincipalTyping.finiteRenamingEq_of_wellFormedElaborationPrincipalityComplete
#print axioms TypePM.Source.M3DeclarationsRegression.list_pattern_wellFormed
#print axioms TypePM.Source.M3DeclarationsRegression.list_pattern_closed
#print axioms TypePM.Source.M3DeclarationsRegression.list_cons_dual_instantiation_exact
#print axioms TypePM.Source.M3DeclarationsRegression.map_instantiation_exact
#print axioms TypePM.Source.M3DeclarationsRegression.paper1_signature_wellFormed
#print axioms TypePM.Source.M3DeclarationsRegression.malformed_list_capability_not_wellFormed
#print axioms TypePM.Source.Paper1FrozenSignature.wellFormed
#print axioms TypePM.Source.FrozenSignature.lookupPatternFunction_unique
#print axioms TypePM.Source.FrozenSignature.lookupPatternFunction_closed
#print axioms TypePM.Source.FrozenSignature.lookupPatternFunction_wellFormed
#print axioms TypePM.Source.M4FrozenSignatureRegression.one_pattern_function_wellFormed
#print axioms TypePM.Source.M4FrozenSignatureRegression.lookup_emptyList_exact
#print axioms TypePM.Source.M4FrozenSignatureRegression.duplicate_pattern_function_not_wellFormed
#print axioms TypePM.Source.PPat.holesInSourceOrder_nodup
#print axioms TypePM.Source.PPat.captureSlots_nodup
#print axioms TypePM.Source.PPat.hole_capture_slots_disjoint
#print axioms TypePM.Source.DPat.bindingsInSourceOrder_nodup
#print axioms TypePM.Source.DPat.bindingSlots_nodup
#print axioms TypePM.Source.capture_data_binding_slots_disjoint
#print axioms TypePM.Source.M4MatcherPatternRegression.all_seven_headers_shapeOK
#print axioms TypePM.Source.M4MatcherPatternRegression.all_seven_headers_capture_order
#print axioms TypePM.Source.M4MatcherPatternRegression.value_cons_summary_exact
#print axioms TypePM.Source.M4MatcherPatternRegression.capture_after_hole_rejected
#print axioms TypePM.Source.M4MatcherPatternRegression.hole_counts_zero_one_two
#print axioms TypePM.Source.M4MatcherPatternRegression.all_seven_capture_counts_exact
#print axioms TypePM.Source.M4MatcherPatternRegression.data_arms_shapeOK
#print axioms TypePM.Source.M4MatcherPatternRegression.data_arm_bindings_exact
#print axioms TypePM.Source.M4MatcherPatternRegression.bad_constructor_arities_rejected
