import TypePM.Syntax

/-!
# Constraint data generated by M1 syntax

These structures are immutable outputs of syntax-directed generation.  They
contain no solver state, branch rollback, or terminal audit.
-/

namespace TypePM

/-- A two-sorted equality that must hold independently of any checking
conversion. -/
inductive Equation where
  | ty (left right : Ty)
  | cap (left right : Cap)
deriving Repr

/-- A raw source type that must later be checked against an expected type. -/
structure CheckObligation where
  source : Ty
  expected : Ty
deriving Repr

/-- Constraints and raw result generated for one expression. -/
structure Generated where
  target : Ty
  hard : List Equation
  pending : List CheckObligation
deriving Repr

/-- List counterpart used while generating a tuple. -/
structure GeneratedItems where
  targets : List Ty
  hard : List Equation
  pending : List CheckObligation
deriving Repr

end TypePM
