import TypePM.Source.PolymorphicLetInferenceOrdinaryStructuralFragment

/-!
# Executable checker for the structurally ordinary source fragment

The explicit `RootOrdinarySourceFragment` certificate is syntax directed, so
it admits a Boolean decision procedure which does not run elaboration or
inference.  The mutually recursive checks below mirror the expression,
tuple-item, and call-argument certificates exactly.  In particular, a `letE`
checks only its body, just as the proposition does: obligations generated by
the internally closed right-hand side are not part of the root block.

The public-inference theorem keeps the two requirements separate.  Boolean
fragment acceptance supplies the ordinary-resolution certificate, while an
independent successful inference run supplies the generated root block.  It
does not state that arbitrary inference success implies fragment acceptance.
-/

namespace TypePM.Source

/-- Decide whether an expression has a syntax-fixed `Int` or function result
in an application-argument position. -/
def ordinaryArgumentResultCheck : Expr → Bool
  | .lit _ | .lam _ => true
  | _ => false

/-- The result-shape check decides exactly `OrdinaryArgumentResult`. -/
theorem ordinaryArgumentResultCheck_eq_true_iff {expression : Expr} :
    ordinaryArgumentResultCheck expression = true ↔
      OrdinaryArgumentResult expression := by
  cases expression with
  | lit value =>
      constructor
      · intro _
        exact .lit value
      · intro _
        rfl
  | lam body =>
      constructor
      · intro _
        exact .lam body
      · intro _
        rfl
  | var index =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | something =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | app function argument =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | tuple items =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | letE value body =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | ctor constructor arguments =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | prim operation arguments =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | ifE condition thenBranch elseBranch =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | fixE body =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | matcher clauses =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | matchAll target matcher pattern body =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result
  | matchFirst target matcher arms fallback =>
      constructor
      · intro checked
        cases checked
      · intro result
        cases result

mutual

  /-- Decide the explicit root-ordinary source fragment without elaborating
  the expression. -/
  def rootOrdinarySourceFragmentCheck : Expr → Bool
    | .var _ | .lit _ | .something => true
    | .lam body => rootOrdinarySourceFragmentCheck body
    | .app function argument =>
        rootOrdinarySourceFragmentCheck function &&
          (rootOrdinarySourceFragmentCheck argument &&
            ordinaryArgumentResultCheck argument)
    | .tuple items => rootOrdinarySourceItemsCheck items
    | .letE _ body => rootOrdinarySourceFragmentCheck body
    | .ctor _ arguments | .prim _ arguments =>
        rootOrdinaryCallArgumentsCheck arguments
    | .ifE condition thenBranch elseBranch =>
        rootOrdinaryCallArgumentsCheck [condition, thenBranch, elseBranch]
    | .fixE _ | .matcher _ | .matchAll _ _ _ _ | .matchFirst _ _ _ _ => false
  termination_by expression => expression.complexity * 3 + 2
  decreasing_by
    all_goals simp_wf
    all_goals try simp
    all_goals omega

  /-- Pointwise Boolean traversal for tuple children. -/
  def rootOrdinarySourceItemsCheck : List Expr → Bool
    | [] => true
    | item :: items =>
        rootOrdinarySourceFragmentCheck item &&
          rootOrdinarySourceItemsCheck items
  termination_by expressions => Expr.listComplexity expressions * 3 + 1
  decreasing_by
    all_goals simp_wf
    all_goals try simp
    all_goals omega

  /-- Boolean traversal for call arguments, including the required outer
  result-shape check at every argument. -/
  def rootOrdinaryCallArgumentsCheck : List Expr → Bool
    | [] => true
    | argument :: arguments =>
        rootOrdinarySourceFragmentCheck argument &&
          (ordinaryArgumentResultCheck argument &&
            rootOrdinaryCallArgumentsCheck arguments)
  termination_by expressions => Expr.listComplexity expressions * 3
  decreasing_by
    all_goals simp_wf
    all_goals try simp
    all_goals omega

end

mutual

  /-- The expression checker is sound and complete for the explicit fragment
  proposition. -/
  theorem rootOrdinarySourceFragmentCheck_eq_true_iff
      {expression : Expr} :
      rootOrdinarySourceFragmentCheck expression = true ↔
        RootOrdinarySourceFragment expression := by
    cases expression with
    | var index =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro _
          exact .var index
        · intro _
          trivial
    | lit value =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro _
          exact .lit value
        · intro _
          trivial
    | something =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro _
          exact .something
        · intro _
          trivial
    | lam body =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          exact .lam (rootOrdinarySourceFragmentCheck_eq_true_iff.mp checked)
        · intro fragment
          cases fragment with
          | lam bodyFragment =>
              exact rootOrdinarySourceFragmentCheck_eq_true_iff.mpr bodyFragment
    | app function argument =>
        simp only [rootOrdinarySourceFragmentCheck, Bool.and_eq_true]
        constructor
        · rintro ⟨functionChecked, argumentChecked, resultChecked⟩
          exact .app
            (rootOrdinarySourceFragmentCheck_eq_true_iff.mp functionChecked)
            (rootOrdinarySourceFragmentCheck_eq_true_iff.mp argumentChecked)
            (ordinaryArgumentResultCheck_eq_true_iff.mp resultChecked)
        · intro fragment
          cases fragment with
          | app functionFragment argumentFragment argumentResult =>
              exact ⟨
                rootOrdinarySourceFragmentCheck_eq_true_iff.mpr functionFragment,
                rootOrdinarySourceFragmentCheck_eq_true_iff.mpr argumentFragment,
                ordinaryArgumentResultCheck_eq_true_iff.mpr argumentResult⟩
    | tuple items =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          exact .tuple (rootOrdinarySourceItemsCheck_eq_true_iff.mp checked)
        · intro fragment
          cases fragment with
          | tuple itemFragments =>
              exact rootOrdinarySourceItemsCheck_eq_true_iff.mpr itemFragments
    | letE value body =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          exact .letE value
            (rootOrdinarySourceFragmentCheck_eq_true_iff.mp checked)
        · intro fragment
          cases fragment with
          | letE _ bodyFragment =>
              exact rootOrdinarySourceFragmentCheck_eq_true_iff.mpr bodyFragment
    | ctor constructor arguments =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          exact .ctor constructor
            (rootOrdinaryCallArgumentsCheck_eq_true_iff.mp checked)
        · intro fragment
          cases fragment with
          | ctor _ argumentFragments =>
              exact rootOrdinaryCallArgumentsCheck_eq_true_iff.mpr
                argumentFragments
    | prim operation arguments =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          exact .prim operation
            (rootOrdinaryCallArgumentsCheck_eq_true_iff.mp checked)
        · intro fragment
          cases fragment with
          | prim _ argumentFragments =>
              exact rootOrdinaryCallArgumentsCheck_eq_true_iff.mpr
                argumentFragments
    | ifE condition thenBranch elseBranch =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          exact .ifE (rootOrdinaryCallArgumentsCheck_eq_true_iff.mp checked)
        · intro fragment
          cases fragment with
          | ifE argumentFragments =>
              exact rootOrdinaryCallArgumentsCheck_eq_true_iff.mpr
                argumentFragments
    | fixE body =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          cases checked
        · intro fragment
          cases fragment
    | matcher clauses =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          cases checked
        · intro fragment
          cases fragment
    | matchAll target matcher pattern body =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          cases checked
        · intro fragment
          cases fragment
    | matchFirst target matcher arms fallback =>
        simp only [rootOrdinarySourceFragmentCheck]
        constructor
        · intro checked
          cases checked
        · intro fragment
          cases fragment
  termination_by expression.complexity * 3 + 2
  decreasing_by
    all_goals simp_wf
    all_goals subst_vars
    all_goals try simp
    all_goals omega

  /-- The tuple-item checker is sound and complete for its pointwise
  certificate. -/
  theorem rootOrdinarySourceItemsCheck_eq_true_iff
      {expressions : List Expr} :
      rootOrdinarySourceItemsCheck expressions = true ↔
        RootOrdinarySourceItems expressions := by
    cases expressions with
    | nil =>
        simp only [rootOrdinarySourceItemsCheck]
        constructor
        · intro _
          exact .nil
        · intro _
          trivial
    | cons item items =>
        simp only [rootOrdinarySourceItemsCheck, Bool.and_eq_true]
        constructor
        · rintro ⟨itemChecked, itemsChecked⟩
          exact .cons
            (rootOrdinarySourceFragmentCheck_eq_true_iff.mp itemChecked)
            (rootOrdinarySourceItemsCheck_eq_true_iff.mp itemsChecked)
        · intro fragments
          cases fragments with
          | cons itemFragment itemFragments =>
              exact ⟨
                rootOrdinarySourceFragmentCheck_eq_true_iff.mpr itemFragment,
                rootOrdinarySourceItemsCheck_eq_true_iff.mpr itemFragments⟩
  termination_by Expr.listComplexity expressions * 3 + 1
  decreasing_by
    all_goals simp_wf
    all_goals subst_vars
    all_goals try simp
    all_goals omega

  /-- The call-argument checker is sound and complete for the conjunction of
  fragment membership and ordinary outer result shape at every position. -/
  theorem rootOrdinaryCallArgumentsCheck_eq_true_iff
      {expressions : List Expr} :
      rootOrdinaryCallArgumentsCheck expressions = true ↔
        RootOrdinaryCallArguments expressions := by
    cases expressions with
    | nil =>
        simp only [rootOrdinaryCallArgumentsCheck]
        constructor
        · intro _
          exact .nil
        · intro _
          trivial
    | cons argument arguments =>
        simp only [rootOrdinaryCallArgumentsCheck, Bool.and_eq_true]
        constructor
        · rintro ⟨argumentChecked, resultChecked, argumentsChecked⟩
          exact .cons
            (rootOrdinarySourceFragmentCheck_eq_true_iff.mp argumentChecked)
            (ordinaryArgumentResultCheck_eq_true_iff.mp resultChecked)
            (rootOrdinaryCallArgumentsCheck_eq_true_iff.mp argumentsChecked)
        · intro fragments
          cases fragments with
          | cons argumentFragment argumentResult argumentFragments =>
              exact ⟨
                rootOrdinarySourceFragmentCheck_eq_true_iff.mpr argumentFragment,
                ordinaryArgumentResultCheck_eq_true_iff.mpr argumentResult,
                rootOrdinaryCallArgumentsCheck_eq_true_iff.mpr
                  argumentFragments⟩
  termination_by Expr.listComplexity expressions * 3
  decreasing_by
    all_goals simp_wf
    all_goals subst_vars
    all_goals try simp
    all_goals omega

end

/-- Boolean fragment acceptance constructs the reusable root structural
certificate, without asserting that elaboration or inference succeeds. -/
theorem rootOrdinarySourceFragmentCheck_rootStructural
    {signature : Signature} {context : Context} {expression : Expr}
    (checked : rootOrdinarySourceFragmentCheck expression = true)
    (wellFormed : signature.WellFormed) :
    InferenceRootResolutionsOrdinaryStructural signature context expression :=
  (rootOrdinarySourceFragmentCheck_eq_true_iff.mp checked).rootStructural
    wellFormed

/-- Boolean fragment acceptance and an independent successful public
inference run make the executable root structural checker accept. -/
theorem rootOrdinarySourceFragmentCheck_inferenceRootStructuralCheck
    {signature : Signature} {context : Context} {expression : Expr}
    {target : Ty}
    (checked : rootOrdinarySourceFragmentCheck expression = true)
    (wellFormed : signature.WellFormed)
    (success : infer signature context expression = some target) :
    inferenceRootStructuralOrdinaryCheck signature context expression = true :=
  RootOrdinarySourceFragment.inferenceRootStructuralCheck
    (rootOrdinarySourceFragmentCheck_eq_true_iff.mp checked)
    wellFormed success

end TypePM.Source
