import TypePM.Source.PolymorphicLetInferenceOrdinaryStructural

/-!
# Executable checker for structural ordinary resolutions

The structural certificate records where every ordinary application
obligation arose in an actual relational source elaboration.  The Boolean
checker below computes on that elaboration's generated root pending list.
Its correctness theorem is an equivalence: the checker accepts exactly when
the existing structural certificate can be constructed.

This is deliberately not a theorem that arbitrary successful inference is
ordinary.  A caller must run the check on the actual generated block and the
substitution selected by hard saturation.  In particular, every special
matcher-to-slot conversion is rejected.
-/

namespace TypePM.Source

/-- Check whether every root obligation generated by this exact relational
elaboration selects ordinary equality under `substitution`.

The elaboration argument ties the executable list traversal to the actual
source derivation; the computation itself only needs its indexed generated
block. -/
def elaborationResolutionsOrdinaryCheckAt
    (substitution : Subst)
    {signature : Signature} {context : Context} {expression : Expr}
    {supply : Supply} {generated : Generated} {next : Supply}
    (_elaboration : Elaborates signature context expression supply generated
      next) : Bool :=
  generated.pending.all fun obligation =>
    (obligation.resolutionUnder substitution).conversionClass == .ordinary

/-- The Boolean traversal decides the existing node-by-node structural
certificate.  The reverse direction is important: the checker is complete,
not merely a sufficient syntactic filter. -/
theorem elaborationResolutionsOrdinaryCheckAt_eq_true_iff
    {substitution : Subst}
    {signature : Signature} {context : Context} {expression : Expr}
    {supply : Supply} {generated : Generated} {next : Supply}
    {elaboration : Elaborates signature context expression supply generated
      next} :
    elaborationResolutionsOrdinaryCheckAt substitution elaboration = true ↔
      ElaborationResolutionsOrdinaryAt substitution elaboration := by
  constructor
  · intro checked
    apply ElaborationResolutionsOrdinaryAt.of_pending elaboration
    intro obligation membership
    simp only [elaborationResolutionsOrdinaryCheckAt, List.all_eq_true,
      beq_iff_eq] at checked
    exact checked obligation membership
  · intro structural
    simp only [elaborationResolutionsOrdinaryCheckAt, List.all_eq_true,
      beq_iff_eq]
    exact structural.pending

/-- A checked actual elaboration constructs the structural proof object used
by the protected runtime bridge. -/
theorem ElaborationResolutionsOrdinaryAt.of_check
    {substitution : Subst}
    {signature : Signature} {context : Context} {expression : Expr}
    {supply : Supply} {generated : Generated} {next : Supply}
    {elaboration : Elaborates signature context expression supply generated
      next}
    (checked : elaborationResolutionsOrdinaryCheckAt substitution elaboration =
      true) :
    ElaborationResolutionsOrdinaryAt substitution elaboration :=
  elaborationResolutionsOrdinaryCheckAt_eq_true_iff.mp checked

/-- Conversely, a structural proof always makes the executable checker
accept. -/
theorem ElaborationResolutionsOrdinaryAt.check
    {substitution : Subst}
    {signature : Signature} {context : Context} {expression : Expr}
    {supply : Supply} {generated : Generated} {next : Supply}
    {elaboration : Elaborates signature context expression supply generated
      next}
    (structural : ElaborationResolutionsOrdinaryAt substitution elaboration) :
    elaborationResolutionsOrdinaryCheckAt substitution elaboration = true :=
  elaborationResolutionsOrdinaryCheckAt_eq_true_iff.mpr structural

/-- The existing root Boolean check now constructs the stronger structural
certificate, rather than stopping at an unstructured list property. -/
theorem InferenceRootResolutionsOrdinaryStructural.of_check
    {signature : Signature} {context : Context} {expression : Expr}
    (wellFormed : signature.WellFormed)
    (checked : inferenceRootPendingResolutionsOrdinaryCheck signature context
      expression = true) :
    InferenceRootResolutionsOrdinaryStructural signature context expression :=
  InferenceRootResolutionsOrdinaryStructural.of_rootPending wellFormed (by
    intro generated next elaborated
    simp only [inferenceRootPendingResolutionsOrdinaryCheck,
      inferenceRootPendingResolutionsOrdinaryCheckUsing, elaborated] at checked
    exact RootPendingResolutionsOrdinary.of_check checked)

namespace PolymorphicLetInferenceOrdinaryStructuralChecker

/-- The executable list traversal rejects the canonical special
matcher-to-slot obligation. -/
theorem matcherToSlot_pendingCheck_rejected :
    ([CheckObligation.mk (.matcher .any .int) (.slot .any .int)]).all
      (fun obligation =>
        (obligation.resolutionUnder Subst.id).conversionClass == .ordinary) =
      false := by
  rfl

/-- Hard saturation does not turn the same special conversion into an
ordinary root certificate. -/
theorem matcherToSlot_rootCheck_rejected :
    rootPendingResolutionsOrdinaryCheckUsing (unifyWithFuel 100)
      { target := .slot .any .int
        hard := []
        pending := [CheckObligation.mk (.matcher .any .int)
          (.slot .any .int)] } = false := by
  with_unfolding_all rfl

end PolymorphicLetInferenceOrdinaryStructuralChecker
end TypePM.Source
