import TypePM.Runtime.DepthFirstSearch

/-!
# Fair finite-prefix search of a binary reduction tree

This module implements the binary reduction tree from the APLAS 2018
description of Egison's search.  A node is a finite list of states, and a
frontier is a finite list of nodes.  In one round, the head state of every
node is stepped.  Nodes generated by those head steps (the left children) are
placed before the nonempty tails of the old nodes (the right children).

The observable result is deliberately a finite prefix: it contains the
answers seen in the requested number of rounds and the remaining frontier.
It does not attempt to construct one completed list of all answers.

Both nodes and frontiers are finite `List`s here.  Consequently this module
does not yet model a genuinely lazy or infinite successor list, nor does it
connect the prefix interface to expression-level lazy `Value`s.
-/

namespace TypePM.Runtime

/-- One observable finite prefix of fair reduction-tree search. -/
structure FairSearchPrefix (State : Type u) (Answer : Type v) where
  answers : List Answer
  frontier : List (List State)
deriving Repr, DecidableEq

/-- The frontier is executable state, so completion is decidable without
forcing any future answers. -/
def FairSearchPrefix.isComplete (snapshot : FairSearchPrefix State Answer) : Bool :=
  snapshot.frontier.all List.isEmpty

@[simp] theorem FairSearchPrefix.isComplete_eq_true_iff
    (snapshot : FairSearchPrefix State Answer) :
    snapshot.isComplete = true ↔
      ∀ node, node ∈ snapshot.frontier → node = [] := by
  rcases snapshot with ⟨answers, frontier⟩
  induction frontier with
  | nil => simp [FairSearchPrefix.isComplete]
  | cons node frontier ih =>
      cases node with
      | nil => simp [FairSearchPrefix.isComplete]
      | cons state tail => simp [FairSearchPrefix.isComplete]

/-- Intermediate products of one breadth-first round.  Left and right nodes
are kept separate until all current nodes have been visited, which fixes the
next-frontier order to all left children followed by all right children. -/
structure FairRound (State : Type u) (Answer : Type v) where
  answers : List Answer
  leftNodes : List (List State)
  rightNodes : List (List State)
deriving Repr, DecidableEq

def FairRound.empty : FairRound State Answer :=
  ⟨[], [], []⟩

/-- Empty state lists are not reduction-tree nodes. -/
def nonemptyNode : List State → List (List State)
  | [] => []
  | state :: states => [state :: states]

/-- Visit the head of every node in one finite frontier. -/
def fairReductionRound
    (step : State → FuelResult (SearchStep State Answer)) :
    List (List State) → FuelResult (FairRound State Answer)
  | [] => .ok .empty
  | [] :: frontier => fairReductionRound step frontier
  | (state :: tail) :: frontier =>
      FuelResult.bind (step state) fun observation =>
        FuelResult.map (fun rest =>
          let rightNodes := nonemptyNode tail ++ rest.rightNodes
          match observation with
          | .yield answer =>
              { answers := answer :: rest.answers
                leftNodes := rest.leftNodes
                rightNodes := rightNodes }
          | .expand successors =>
              { answers := rest.answers
                leftNodes := nonemptyNode successors ++ rest.leftNodes
                rightNodes := rightNodes })
          (fairReductionRound step frontier)

/-- Add one completed round to an accumulated prefix. -/
def FairSearchPrefix.advance
    (snapshot : FairSearchPrefix State Answer)
    (round : FairRound State Answer) : FairSearchPrefix State Answer :=
  { answers := snapshot.answers ++ round.answers
    frontier := round.leftNodes ++ round.rightNodes }

/-- Run a fixed number of complete breadth-first rounds from an existing
prefix.  Round exhaustion returns the prefix and frontier rather than a
`timeout`; an underlying state step can still return `timeout`. -/
def fairReductionRounds
    (step : State → FuelResult (SearchStep State Answer)) :
    Nat → FairSearchPrefix State Answer →
      FuelResult (FairSearchPrefix State Answer)
  | 0, snapshot => .ok snapshot
  | rounds + 1, snapshot =>
      FuelResult.bind (fairReductionRound step snapshot.frontier) fun round =>
        fairReductionRounds step rounds (snapshot.advance round)

/-- Observe a finite fair-search prefix starting from one reduction-tree
node. -/
def fairReductionPrefix
    (step : State → FuelResult (SearchStep State Answer))
    (rounds : Nat) (states : List State) :
    FuelResult (FairSearchPrefix State Answer) :=
  fairReductionRounds step rounds
    { answers := [], frontier := nonemptyNode states }

/-- Pointwise safety for a finite list. -/
def AllSafe (Safe : α → Prop) (values : List α) : Prop :=
  ∀ value, value ∈ values → Safe value

/-- Every state stored anywhere in the frontier is safe. -/
def FairFrontierSafe
    (StateSafe : State → Prop) (frontier : List (List State)) : Prop :=
  ∀ node, node ∈ frontier → AllSafe StateSafe node

/-- Safety of a successful single-step observation. -/
def SearchStepSafe
    (StateSafe : State → Prop) (AnswerSafe : Answer → Prop) :
    SearchStep State Answer → Prop
  | .yield answer => AnswerSafe answer
  | .expand successors => AllSafe StateSafe successors

/-- A caller-selected state invariant is preserved by every successful step,
and yielded answers satisfy the caller-selected answer invariant. -/
def FairStepPreserves
    (step : State → FuelResult (SearchStep State Answer))
    (StateSafe : State → Prop) (AnswerSafe : Answer → Prop) : Prop :=
  ∀ state observation, StateSafe state → step state = .ok observation →
    SearchStepSafe StateSafe AnswerSafe observation

/-- Safe states cannot take the runtime coverage-failure result `stuck`. -/
def FairStepNotStuck
    (step : State → FuelResult (SearchStep State Answer))
    (StateSafe : State → Prop) : Prop :=
  ∀ state, StateSafe state → (step state).NotStuck

def FairRound.Safe
    (StateSafe : State → Prop) (AnswerSafe : Answer → Prop)
    (round : FairRound State Answer) : Prop :=
  AllSafe AnswerSafe round.answers ∧
    FairFrontierSafe StateSafe round.leftNodes ∧
    FairFrontierSafe StateSafe round.rightNodes

def FairSearchPrefix.Safe
    (StateSafe : State → Prop) (AnswerSafe : Answer → Prop)
    (snapshot : FairSearchPrefix State Answer) : Prop :=
  AllSafe AnswerSafe snapshot.answers ∧
    FairFrontierSafe StateSafe snapshot.frontier

theorem AllSafe.append
    {Safe : α → Prop} {left right : List α}
    (leftSafe : AllSafe Safe left) (rightSafe : AllSafe Safe right) :
    AllSafe Safe (left ++ right) := by
  intro value member
  rw [List.mem_append] at member
  cases member with
  | inl member => exact leftSafe value member
  | inr member => exact rightSafe value member

theorem FairFrontierSafe.append
    {StateSafe : State → Prop}
    {left right : List (List State)}
    (leftSafe : FairFrontierSafe StateSafe left)
    (rightSafe : FairFrontierSafe StateSafe right) :
    FairFrontierSafe StateSafe (left ++ right) := by
  intro node member
  rw [List.mem_append] at member
  cases member with
  | inl member => exact leftSafe node member
  | inr member => exact rightSafe node member

theorem nonemptyNode_safe
    {StateSafe : State → Prop} {states : List State}
    (safe : AllSafe StateSafe states) :
    FairFrontierSafe StateSafe (nonemptyNode states) := by
  cases states with
  | nil => simp [nonemptyNode, FairFrontierSafe]
  | cons state tail =>
      intro node nodeMember
      simp only [nonemptyNode, List.mem_singleton] at nodeMember
      subst node
      exact safe

/-- One successful round preserves both selected safety predicates. -/
theorem fairReductionRound_safe
    {step : State → FuelResult (SearchStep State Answer)}
    {StateSafe : State → Prop} {AnswerSafe : Answer → Prop}
    (preserves : FairStepPreserves step StateSafe AnswerSafe)
    {frontier : List (List State)}
    (frontierSafe : FairFrontierSafe StateSafe frontier)
    {round : FairRound State Answer}
    (success : fairReductionRound step frontier = .ok round) :
    round.Safe StateSafe AnswerSafe := by
  induction frontier generalizing round with
  | nil =>
      simp only [fairReductionRound] at success
      cases success
      simp [FairRound.Safe, FairRound.empty, AllSafe, FairFrontierSafe]
  | cons node frontier ih =>
      have tailSafe : FairFrontierSafe StateSafe frontier := by
        intro candidate member
        exact frontierSafe candidate (by simp [member])
      cases node with
      | nil =>
          exact ih tailSafe success
      | cons state tail =>
          have stateSafe : StateSafe state :=
            frontierSafe (state :: tail) (by simp) state (by simp)
          simp only [fairReductionRound] at success
          rw [FuelResult.bind_eq_ok_iff] at success
          rcases success with ⟨observation, stepped, continued⟩
          rw [FuelResult.map_eq_ok_iff] at continued
          rcases continued with ⟨rest, restResult, outputEq⟩
          have restSafe := ih tailSafe restResult
          have observationSafe := preserves state observation stateSafe stepped
          cases observation with
          | yield answer =>
              simp only at outputEq
              subst round
              rcases restSafe with ⟨answersSafe, leftSafe, rightSafe⟩
              refine ⟨?_, leftSafe, ?_⟩
              · intro candidate member
                simp only [List.mem_cons] at member
                cases member with
                | inl equal =>
                    subst candidate
                    exact observationSafe
                | inr member => exact answersSafe candidate member
              · exact FairFrontierSafe.append
                  (nonemptyNode_safe (by
                    intro candidate member
                    exact frontierSafe (state :: tail) (by simp)
                      candidate (by simp [member])))
                  rightSafe
          | expand successors =>
              simp only at outputEq
              subst round
              rcases restSafe with ⟨answersSafe, leftSafe, rightSafe⟩
              refine ⟨answersSafe, ?_, ?_⟩
              · exact FairFrontierSafe.append
                  (nonemptyNode_safe observationSafe) leftSafe
              · exact FairFrontierSafe.append
                  (nonemptyNode_safe (by
                    intro candidate member
                    exact frontierSafe (state :: tail) (by simp)
                      candidate (by simp [member])))
                  rightSafe

/-- No safe frontier can make one fair round return `stuck`. -/
theorem fairReductionRound_notStuck
    {step : State → FuelResult (SearchStep State Answer)}
    {StateSafe : State → Prop}
    (stepSafe : FairStepNotStuck step StateSafe)
    (frontier : List (List State))
    (frontierSafe : FairFrontierSafe StateSafe frontier) :
    (fairReductionRound step frontier).NotStuck := by
  induction frontier with
  | nil => trivial
  | cons node frontier ih =>
      have tailSafe : FairFrontierSafe StateSafe frontier := by
        intro candidate member
        exact frontierSafe candidate (by simp [member])
      cases node with
      | nil => exact ih tailSafe
      | cons state tail =>
          simp only [fairReductionRound]
          apply FuelResult.bind_notStuck
            (resultSafe := stepSafe state
              (frontierSafe (state :: tail) (by simp) state (by simp)))
          intro observation
          exact FuelResult.map_notStuck _ (ih tailSafe)

/-- Advancing by a safe round preserves accumulated prefix safety. -/
theorem FairSearchPrefix.advance_safe
    {snapshot : FairSearchPrefix State Answer}
    {round : FairRound State Answer}
    (prefixSafe : snapshot.Safe StateSafe AnswerSafe)
    (roundSafe : round.Safe StateSafe AnswerSafe) :
    (snapshot.advance round).Safe StateSafe AnswerSafe := by
  rcases prefixSafe with ⟨prefixAnswers, prefixFrontier⟩
  rcases roundSafe with ⟨roundAnswers, leftSafe, rightSafe⟩
  exact ⟨AllSafe.append prefixAnswers roundAnswers,
    FairFrontierSafe.append leftSafe rightSafe⟩

/-- Every successful finite-round execution preserves prefix and frontier
safety. -/
theorem fairReductionRounds_safe
    {step : State → FuelResult (SearchStep State Answer)}
    {StateSafe : State → Prop} {AnswerSafe : Answer → Prop}
    (preserves : FairStepPreserves step StateSafe AnswerSafe)
    (rounds : Nat) {snapshot output : FairSearchPrefix State Answer}
    (prefixSafe : snapshot.Safe StateSafe AnswerSafe)
    (success : fairReductionRounds step rounds snapshot = .ok output) :
    output.Safe StateSafe AnswerSafe := by
  induction rounds generalizing snapshot output with
  | zero =>
      simp only [fairReductionRounds] at success
      cases success
      exact prefixSafe
  | succ rounds ih =>
      simp only [fairReductionRounds] at success
      rw [FuelResult.bind_eq_ok_iff] at success
      rcases success with ⟨round, roundResult, continued⟩
      have roundSafe := fairReductionRound_safe preserves
        prefixSafe.2 roundResult
      exact ih (snapshot.advance_safe prefixSafe roundSafe) continued

/-- A safe finite-round execution cannot return `stuck`; incomplete work is
represented by the returned frontier, while a state-level timeout remains
`timeout`. -/
theorem fairReductionRounds_notStuck
    {step : State → FuelResult (SearchStep State Answer)}
    {StateSafe : State → Prop} {AnswerSafe : Answer → Prop}
    (preserves : FairStepPreserves step StateSafe AnswerSafe)
    (stepSafe : FairStepNotStuck step StateSafe)
    (rounds : Nat) (snapshot : FairSearchPrefix State Answer)
    (prefixSafe : snapshot.Safe StateSafe AnswerSafe) :
    (fairReductionRounds step rounds snapshot).NotStuck := by
  induction rounds generalizing snapshot with
  | zero => trivial
  | succ rounds ih =>
      cases result : fairReductionRound step snapshot.frontier with
      | timeout => simp [fairReductionRounds, result, FuelResult.NotStuck]
      | stuck =>
          have contradiction := fairReductionRound_notStuck stepSafe
            snapshot.frontier prefixSafe.2
          simp [result, FuelResult.NotStuck] at contradiction
      | ok round =>
          simp only [fairReductionRounds, result, FuelResult.bind_ok]
          have roundSafe := fairReductionRound_safe preserves
            prefixSafe.2 result
          exact ih (snapshot.advance round)
            (snapshot.advance_safe prefixSafe roundSafe)

/-- Successful public-prefix execution preserves caller-selected state and
answer invariants. -/
theorem fairReductionPrefix_safe
    {step : State → FuelResult (SearchStep State Answer)}
    {StateSafe : State → Prop} {AnswerSafe : Answer → Prop}
    (preserves : FairStepPreserves step StateSafe AnswerSafe)
    (rounds : Nat) {states : List State}
    (statesSafe : AllSafe StateSafe states)
    {output : FairSearchPrefix State Answer}
    (success : fairReductionPrefix step rounds states = .ok output) :
    output.Safe StateSafe AnswerSafe := by
  apply fairReductionRounds_safe preserves rounds
    (snapshot := { answers := [], frontier := nonemptyNode states })
  · exact ⟨by simp [AllSafe], nonemptyNode_safe statesSafe⟩
  · exact success

/-- The public finite-prefix search is non-stuck under the same caller-owned
invariants used by the preservation theorem. -/
theorem fairReductionPrefix_notStuck
    {step : State → FuelResult (SearchStep State Answer)}
    {StateSafe : State → Prop} {AnswerSafe : Answer → Prop}
    (preserves : FairStepPreserves step StateSafe AnswerSafe)
    (stepSafe : FairStepNotStuck step StateSafe)
    (rounds : Nat) (states : List State)
    (statesSafe : AllSafe StateSafe states) :
    (fairReductionPrefix step rounds states).NotStuck := by
  apply fairReductionRounds_notStuck preserves stepSafe rounds
    { answers := [], frontier := nonemptyNode states }
  exact ⟨by simp [AllSafe], nonemptyNode_safe statesSafe⟩

end TypePM.Runtime
