import TypePM.Runtime.FairReductionTreeSearch

/-!
# Finite reachability completeness of fair reduction-tree search

This module gives the binary reduction tree an independent relational
specification.  A left edge enters the nonempty successor list generated by a
node's head state.  A right edge enters the nonempty tail of that node.  The
finite-depth reachability relation is not defined through the executable fair
search or its returned frontier.

The main theorem states the appropriate finite observation property: if every
state at every reachable level through `d` takes a completed (`ok`) step, then
an answer yielded by a node at depth `d` occurs in the answer prefix after
`d + 1` fair rounds.  Successor collections are finite `List`s throughout.
This is finite-prefix completeness, not production of a completed list of all
answers or a theorem about genuinely lazy/infinite successor collections.
-/

namespace TypePM.Runtime

/-- The left edge of the binary reduction tree enters the finite successor
list generated by the head state. -/
def ReductionLeftChild
    (step : State → FuelResult (SearchStep State Answer))
    (parent child : List State) : Prop :=
  ∃ state tail successors,
    parent = state :: tail ∧
    step state = .ok (.expand successors) ∧
    successors ≠ [] ∧
    child = successors

/-- The right edge of the binary reduction tree enters the nonempty tail of
the parent node.  It does not depend on whether the head yields or expands. -/
def ReductionRightChild (parent child : List State) : Prop :=
  ∃ state tail,
    parent = state :: tail ∧ tail ≠ [] ∧ child = tail

def ReductionChild
    (step : State → FuelResult (SearchStep State Answer))
    (parent child : List State) : Prop :=
  ReductionLeftChild step parent child ∨ ReductionRightChild parent child

/-- Independent finite-depth reachability in the binary reduction tree. -/
inductive ReductionTreeReachable
    (step : State → FuelResult (SearchStep State Answer))
    (root : List State) : Nat → List State → Prop where
  | root (nonempty : root ≠ []) : ReductionTreeReachable step root 0 root
  | next
      (parent : ReductionTreeReachable step root depth node)
      (edge : ReductionChild step node child) :
      ReductionTreeReachable step root (depth + 1) child

/-- A yield at one independently reachable node. -/
def ReductionTreeYields
    (step : State → FuelResult (SearchStep State Answer))
    (root : List State) (depth : Nat) (answer : Answer) : Prop :=
  ∃ state tail,
    ReductionTreeReachable step root depth (state :: tail) ∧
    step state = .ok (.yield answer)

/-- Local totality required for finite fairness: the head of every reachable
node through the selected depth takes some completed step. -/
def ReachableStepsComplete
    (step : State → FuelResult (SearchStep State Answer))
    (root : List State) (throughDepth : Nat) : Prop :=
  ∀ depth, depth ≤ throughDepth → ∀ state tail,
    ReductionTreeReachable step root depth (state :: tail) →
      ∃ observation, step state = .ok observation

theorem ReductionLeftChild.child_nonempty
    {step : State → FuelResult (SearchStep State Answer)}
    {parent child : List State}
    (edge : ReductionLeftChild step parent child) : child ≠ [] := by
  rcases edge with ⟨state, tail, successors, parentEq, stepped,
    nonempty, childEq⟩
  simpa [childEq] using nonempty

theorem ReductionRightChild.child_nonempty
    {parent child : List State}
    (edge : ReductionRightChild parent child) : child ≠ [] := by
  rcases edge with ⟨state, tail, parentEq, nonempty, childEq⟩
  simpa [childEq] using nonempty

theorem ReductionChild.child_nonempty
    {step : State → FuelResult (SearchStep State Answer)}
    {parent child : List State}
    (edge : ReductionChild step parent child) : child ≠ [] := by
  cases edge with
  | inl edge => exact edge.child_nonempty
  | inr edge => exact edge.child_nonempty

theorem ReductionTreeReachable.nonempty
    {step : State → FuelResult (SearchStep State Answer)}
    {root : List State} {depth : Nat} {node : List State}
    (reachable : ReductionTreeReachable step root depth node) : node ≠ [] := by
  induction reachable with
  | root nonempty => exact nonempty
  | next parent edge ih => exact edge.child_nonempty

theorem mem_nonemptyNode_iff
    (candidate states : List State) :
    candidate ∈ nonemptyNode states ↔ states ≠ [] ∧ candidate = states := by
  cases states with
  | nil => simp [nonemptyNode]
  | cons state tail => simp [nonemptyNode]

/-- Independent relational specification of one executable fair round. -/
inductive FairRoundDerivation
    (step : State → FuelResult (SearchStep State Answer)) :
    List (List State) → FairRound State Answer → Prop where
  | nil : FairRoundDerivation step [] .empty
  | empty
      (rest : FairRoundDerivation step frontier round) :
      FairRoundDerivation step ([] :: frontier) round
  | yield
      (head : step state = .ok (.yield answer))
      (rest : FairRoundDerivation step frontier round) :
      FairRoundDerivation step ((state :: tail) :: frontier)
        { answers := answer :: round.answers
          leftNodes := round.leftNodes
          rightNodes := nonemptyNode tail ++ round.rightNodes }
  | expand
      (head : step state = .ok (.expand successors))
      (rest : FairRoundDerivation step frontier round) :
      FairRoundDerivation step ((state :: tail) :: frontier)
        { answers := round.answers
          leftNodes := nonemptyNode successors ++ round.leftNodes
          rightNodes := nonemptyNode tail ++ round.rightNodes }

/-- A relational round executes with exactly the specified products. -/
theorem FairRoundDerivation.complete
    {step : State → FuelResult (SearchStep State Answer)}
    {frontier : List (List State)} {round : FairRound State Answer}
    (derivation : FairRoundDerivation step frontier round) :
    fairReductionRound step frontier = .ok round := by
  induction derivation with
  | nil => rfl
  | empty rest ih => exact ih
  | yield head rest ih => simp [fairReductionRound, head, ih]
  | expand head rest ih => simp [fairReductionRound, head, ih]

/-- If every head in a finite frontier completes, that round has an
independent relational derivation. -/
theorem fairRoundDerivation_exists
    {step : State → FuelResult (SearchStep State Answer)}
    (frontier : List (List State))
    (complete : ∀ state tail, (state :: tail) ∈ frontier →
      ∃ observation, step state = .ok observation) :
    ∃ round, FairRoundDerivation step frontier round := by
  induction frontier with
  | nil => exact ⟨.empty, .nil⟩
  | cons node frontier ih =>
      have restComplete : ∀ state tail, (state :: tail) ∈ frontier →
          ∃ observation, step state = .ok observation := by
        intro state tail member
        exact complete state tail (by simp [member])
      rcases ih restComplete with ⟨round, rest⟩
      cases node with
      | nil => exact ⟨round, .empty rest⟩
      | cons state tail =>
          rcases complete state tail (by simp) with ⟨observation, head⟩
          cases observation with
          | yield answer => exact ⟨_, .yield head rest⟩
          | expand successors => exact ⟨_, .expand head rest⟩

theorem FairRoundDerivation.leftNodes_iff
    {step : State → FuelResult (SearchStep State Answer)}
    {frontier : List (List State)} {round : FairRound State Answer}
    (derivation : FairRoundDerivation step frontier round)
    (child : List State) :
    child ∈ round.leftNodes ↔
      ∃ parent, parent ∈ frontier ∧ ReductionLeftChild step parent child := by
  induction derivation with
  | nil => simp [FairRound.empty, ReductionLeftChild]
  | empty rest ih =>
      simpa [ReductionLeftChild] using ih
  | yield head rest ih =>
      rename_i currentState yieldedAnswer remainingFrontier remainingRound currentTail
      simp only [ih, List.mem_cons]
      constructor
      · rintro ⟨parent, member, edge⟩
        exact ⟨parent, Or.inr member, edge⟩
      · rintro ⟨parent, member, edge⟩
        cases member with
        | inl parentEq =>
            subst parent
            rcases edge with
              ⟨candidate, candidateTail, successors, parentEq,
                expanded, successorsNonempty, childEq⟩
            simp only [List.cons.injEq] at parentEq
            rcases parentEq with ⟨stateEq, tailEq⟩
            subst candidate
            subst candidateTail
            have impossible :
                (SearchStep.yield yieldedAnswer : SearchStep State Answer) =
                  .expand successors := by
              simpa using head.symm.trans expanded
            cases impossible
        | inr member => exact ⟨parent, member, edge⟩
  | expand head rest ih =>
      rename_i currentState successors remainingFrontier remainingRound currentTail
      rw [List.mem_append, mem_nonemptyNode_iff, ih]
      constructor
      · intro member
        cases member with
        | inl generated =>
            refine ⟨currentState :: currentTail, by simp, ?_⟩
            exact ⟨currentState, currentTail, successors, rfl, head,
              generated.1, generated.2⟩
        | inr inherited =>
            rcases inherited with ⟨parent, member, edge⟩
            exact ⟨parent, by simp [member], edge⟩
      · rintro ⟨parent, member, edge⟩
        simp only [List.mem_cons] at member
        cases member with
        | inl parentEq =>
            subst parent
            rcases edge with
              ⟨candidate, candidateTail, generated, parentEq,
                expanded, generatedNonempty, childEq⟩
            simp only [List.cons.injEq] at parentEq
            rcases parentEq with ⟨stateEq, tailEq⟩
            subst candidate
            subst candidateTail
            have generatedEq : generated = successors := by
              simpa using expanded.symm.trans head
            exact Or.inl ⟨by simpa [generatedEq] using generatedNonempty,
              childEq.trans generatedEq⟩
        | inr member => exact Or.inr ⟨parent, member, edge⟩

theorem FairRoundDerivation.rightNodes_iff
    {step : State → FuelResult (SearchStep State Answer)}
    {frontier : List (List State)} {round : FairRound State Answer}
    (derivation : FairRoundDerivation step frontier round)
    (child : List State) :
    child ∈ round.rightNodes ↔
      ∃ parent, parent ∈ frontier ∧ ReductionRightChild parent child := by
  induction derivation with
  | nil => simp [FairRound.empty, ReductionRightChild]
  | empty rest ih => simpa [ReductionRightChild] using ih
  | yield head rest ih =>
      rename_i currentState yieldedAnswer remainingFrontier remainingRound currentTail
      rw [List.mem_append, mem_nonemptyNode_iff, ih]
      constructor
      · intro member
        cases member with
        | inl copied =>
            refine ⟨currentState :: currentTail, by simp, ?_⟩
            exact ⟨currentState, currentTail, rfl, copied.1, copied.2⟩
        | inr inherited =>
            rcases inherited with ⟨parent, member, edge⟩
            exact ⟨parent, by simp [member], edge⟩
      · rintro ⟨parent, member, edge⟩
        simp only [List.mem_cons] at member
        cases member with
        | inl parentEq =>
            subst parent
            rcases edge with
              ⟨candidate, copied, parentEq, copiedNonempty, childEq⟩
            simp only [List.cons.injEq] at parentEq
            rcases parentEq with ⟨stateEq, tailEq⟩
            subst candidate
            exact Or.inl ⟨by simpa [tailEq] using copiedNonempty,
              childEq.trans tailEq.symm⟩
        | inr member => exact Or.inr ⟨parent, member, edge⟩
  | expand head rest ih =>
      rename_i currentState successors remainingFrontier remainingRound currentTail
      rw [List.mem_append, mem_nonemptyNode_iff, ih]
      constructor
      · intro member
        cases member with
        | inl copied =>
            refine ⟨currentState :: currentTail, by simp, ?_⟩
            exact ⟨currentState, currentTail, rfl, copied.1, copied.2⟩
        | inr inherited =>
            rcases inherited with ⟨parent, member, edge⟩
            exact ⟨parent, by simp [member], edge⟩
      · rintro ⟨parent, member, edge⟩
        simp only [List.mem_cons] at member
        cases member with
        | inl parentEq =>
            subst parent
            rcases edge with
              ⟨candidate, copied, parentEq, copiedNonempty, childEq⟩
            simp only [List.cons.injEq] at parentEq
            rcases parentEq with ⟨stateEq, tailEq⟩
            subst candidate
            exact Or.inl ⟨by simpa [tailEq] using copiedNonempty,
              childEq.trans tailEq.symm⟩
        | inr member => exact Or.inr ⟨parent, member, edge⟩

theorem FairRoundDerivation.answers_iff
    {step : State → FuelResult (SearchStep State Answer)}
    {frontier : List (List State)} {round : FairRound State Answer}
    (derivation : FairRoundDerivation step frontier round)
    (answer : Answer) :
    answer ∈ round.answers ↔
      ∃ state tail, (state :: tail) ∈ frontier ∧
        step state = .ok (.yield answer) := by
  induction derivation with
  | nil => simp [FairRound.empty]
  | empty rest ih => simpa using ih
  | yield head rest ih =>
      rename_i currentState yieldedAnswer remainingFrontier remainingRound currentTail
      simp only [List.mem_cons, ih]
      constructor
      · intro member
        cases member with
        | inl answerEq =>
            subst answer
            exact ⟨currentState, currentTail, by simp, head⟩
        | inr inherited =>
            rcases inherited with ⟨state, tail, member, yielded⟩
            exact ⟨state, tail, by simp [member], yielded⟩
      · rintro ⟨candidate, candidateTail, member, yielded⟩
        cases member with
        | inl nodeEq =>
            simp only [List.cons.injEq] at nodeEq
            rcases nodeEq with ⟨stateEq, tailEq⟩
            subst candidate
            subst candidateTail
            have answerEq : answer = yieldedAnswer := by
              simpa using yielded.symm.trans head
            exact Or.inl answerEq
        | inr member =>
            exact Or.inr ⟨candidate, candidateTail, member, yielded⟩
  | expand head rest ih =>
      rename_i currentState successors remainingFrontier remainingRound currentTail
      rw [ih]
      constructor
      · rintro ⟨state, tail, member, yielded⟩
        exact ⟨state, tail, by simp [member], yielded⟩
      · rintro ⟨candidate, candidateTail, member, yielded⟩
        simp only [List.mem_cons] at member
        cases member with
        | inl nodeEq =>
            simp only [List.cons.injEq] at nodeEq
            rcases nodeEq with ⟨stateEq, tailEq⟩
            subst candidate
            subst candidateTail
            have impossible :
                (SearchStep.expand successors : SearchStep State Answer) =
                  .yield answer := by
              simpa using head.symm.trans yielded
            cases impossible
        | inr member => exact ⟨candidate, candidateTail, member, yielded⟩

/-- Membership in the next frontier is exactly one independent left or right
edge from a node in the current frontier. -/
theorem FairRoundDerivation.frontier_iff
    {step : State → FuelResult (SearchStep State Answer)}
    {frontier : List (List State)} {round : FairRound State Answer}
    (derivation : FairRoundDerivation step frontier round)
    (child : List State) :
    child ∈ round.leftNodes ++ round.rightNodes ↔
      ∃ parent, parent ∈ frontier ∧ ReductionChild step parent child := by
  rw [List.mem_append, derivation.leftNodes_iff,
    derivation.rightNodes_iff]
  constructor
  · intro member
    cases member with
    | inl left =>
        rcases left with ⟨parent, parentMember, edge⟩
        exact ⟨parent, parentMember, Or.inl edge⟩
    | inr right =>
        rcases right with ⟨parent, parentMember, edge⟩
        exact ⟨parent, parentMember, Or.inr edge⟩
  · rintro ⟨parent, parentMember, edge⟩
    cases edge with
    | inl edge => exact Or.inl ⟨parent, parentMember, edge⟩
    | inr edge => exact Or.inr ⟨parent, parentMember, edge⟩

/-- A finite frontier represents exactly one depth of the independent
reduction tree. -/
def FrontierAtDepth
    (step : State → FuelResult (SearchStep State Answer))
    (root : List State) (depth : Nat)
    (frontier : List (List State)) : Prop :=
  ∀ node, node ∈ frontier ↔
    ReductionTreeReachable step root depth node

theorem ReductionTreeReachable.root_nonempty
    {step : State → FuelResult (SearchStep State Answer)}
    {root : List State} {depth : Nat} {node : List State}
    (reachable : ReductionTreeReachable step root depth node) : root ≠ [] := by
  induction reachable with
  | root nonempty => exact nonempty
  | next parent edge ih => exact ih

theorem initial_frontier_at_depth_zero
    (step : State → FuelResult (SearchStep State Answer))
    (root : List State) (rootNonempty : root ≠ []) :
    FrontierAtDepth step root 0 (nonemptyNode root) := by
  intro node
  rw [mem_nonemptyNode_iff]
  constructor
  · rintro ⟨nonempty, nodeEq⟩
    subst node
    exact .root rootNonempty
  · intro reachable
    cases reachable with
    | root nonempty => exact ⟨nonempty, rfl⟩

/-- One relational round advances an exact level frontier by one independent
tree depth. -/
theorem FairRoundDerivation.frontier_at_next_depth
    {step : State → FuelResult (SearchStep State Answer)}
    {root : List State} {depth : Nat}
    {frontier : List (List State)} {round : FairRound State Answer}
    (derivation : FairRoundDerivation step frontier round)
    (atDepth : FrontierAtDepth step root depth frontier) :
    FrontierAtDepth step root (depth + 1)
      (round.leftNodes ++ round.rightNodes) := by
  intro child
  rw [derivation.frontier_iff]
  constructor
  · rintro ⟨parent, member, edge⟩
    exact .next ((atDepth parent).mp member) edge
  · intro reachable
    cases reachable with
    | next parent edge =>
        exact ⟨_, (atDepth _).mpr parent, edge⟩

theorem fairRoundDerivation_exists_at_depth
    {step : State → FuelResult (SearchStep State Answer)}
    {root : List State} {depth : Nat}
    {throughDepth : Nat}
    (complete : ReachableStepsComplete step root throughDepth)
    (depthBound : depth ≤ throughDepth)
    (frontier : List (List State))
    (atDepth : FrontierAtDepth step root depth frontier) :
    ∃ round, FairRoundDerivation step frontier round := by
  apply fairRoundDerivation_exists frontier
  intro state tail member
  exact complete depth depthBound state tail ((atDepth _).mp member)

/-- Executing a concatenated number of rounds agrees with executing the first
group and then the second group. -/
theorem fairReductionRounds_add
    (step : State → FuelResult (SearchStep State Answer))
    (first second : Nat) (snapshot : FairSearchPrefix State Answer) :
    fairReductionRounds step (first + second) snapshot =
      FuelResult.bind (fairReductionRounds step first snapshot)
        (fairReductionRounds step second) := by
  induction first generalizing snapshot with
  | zero => simp [fairReductionRounds]
  | succ first ih =>
      simp only [Nat.succ_add, fairReductionRounds]
      cases result : fairReductionRound step snapshot.frontier with
      | timeout => simp
      | stuck => simp
      | ok round => simp [ih]

/-- Starting from any exact level frontier, a finite number of fair rounds
terminates and produces exactly the corresponding later level. -/
theorem fairReductionRounds_represent_depth
    {step : State → FuelResult (SearchStep State Answer)}
    {root : List State}
    {throughDepth : Nat}
    (complete : ReachableStepsComplete step root throughDepth)
    (rounds : Nat) (startDepth : Nat)
    (snapshot : FairSearchPrefix State Answer)
    (atDepth : FrontierAtDepth step root startDepth snapshot.frontier)
    (roundBound : startDepth + rounds ≤ throughDepth + 1) :
    ∃ output,
      fairReductionRounds step rounds snapshot = .ok output ∧
      FrontierAtDepth step root (startDepth + rounds) output.frontier := by
  induction rounds generalizing startDepth snapshot with
  | zero =>
      exact ⟨snapshot, rfl, by simpa using atDepth⟩
  | succ rounds ih =>
      have startBound : startDepth ≤ throughDepth := by omega
      rcases fairRoundDerivation_exists_at_depth complete
        startBound snapshot.frontier atDepth with ⟨round, derivation⟩
      have roundResult := derivation.complete
      have nextDepth := derivation.frontier_at_next_depth atDepth
      rcases ih (startDepth + 1) (snapshot.advance round) nextDepth
          (by omega) with
        ⟨output, continued, outputDepth⟩
      refine ⟨output, ?_, ?_⟩
      · simpa [fairReductionRounds, roundResult] using continued
      · simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
          outputDepth

/-- All nodes at a requested finite depth are present in the returned
frontier after that many fair rounds. -/
theorem fairReductionPrefix_represent_depth
    {step : State → FuelResult (SearchStep State Answer)}
    {root : List State}
    (depth : Nat)
    (complete : ReachableStepsComplete step root depth)
    (rootNonempty : root ≠ []) :
    ∃ output,
      fairReductionPrefix step depth root = .ok output ∧
      FrontierAtDepth step root depth output.frontier := by
  have initial := initial_frontier_at_depth_zero step root rootNonempty
  rcases fairReductionRounds_represent_depth complete depth 0
      { answers := [], frontier := nonemptyNode root } initial (by omega) with
    ⟨output, result, atDepth⟩
  exact ⟨output, result, by simpa using atDepth⟩

/-- Finite fairness of the binary reduction tree.  A yield at independent
tree depth `d` is observed after exactly `d + 1` complete fair rounds. -/
theorem reductionTreeYield_eventually_observed
    {step : State → FuelResult (SearchStep State Answer)}
    {root : List State} {depth : Nat} {answer : Answer}
    (complete : ReachableStepsComplete step root depth)
    (yielded : ReductionTreeYields step root depth answer) :
    ∃ output,
      fairReductionPrefix step (depth + 1) root = .ok output ∧
      answer ∈ output.answers := by
  rcases yielded with ⟨state, tail, reachable, head⟩
  rcases fairReductionPrefix_represent_depth depth complete
      reachable.root_nonempty with ⟨before, beforeResult, atDepth⟩
  rcases fairRoundDerivation_exists_at_depth complete
      (Nat.le_refl depth) before.frontier atDepth with ⟨round, derivation⟩
  have roundResult := derivation.complete
  have answerInRound : answer ∈ round.answers :=
    (derivation.answers_iff answer).mpr
      ⟨state, tail, (atDepth _).mpr reachable, head⟩
  have finalMember : answer ∈ (before.advance round).answers := by
    simp [FairSearchPrefix.advance, answerInRound]
  have finalRound :
      fairReductionRounds step 1 before = .ok (before.advance round) := by
    simp [fairReductionRounds, roundResult]
  have beforeRounds :
      fairReductionRounds step depth
        { answers := [], frontier := nonemptyNode root } = .ok before :=
    beforeResult
  refine ⟨before.advance round, ?_, finalMember⟩
  calc
    fairReductionPrefix step (depth + 1) root =
        fairReductionRounds step (depth + 1)
          { answers := [], frontier := nonemptyNode root } := rfl
    _ = FuelResult.bind
          (fairReductionRounds step depth
            { answers := [], frontier := nonemptyNode root })
          (fairReductionRounds step 1) :=
        fairReductionRounds_add step depth 1 _
    _ = .ok (before.advance round) := by
      simp only [beforeRounds, FuelResult.bind_ok, finalRound]

end TypePM.Runtime
